### ISSUE TITLE
Le mail de l'expéditeur ne s'affiche pas 

### ISSUE THREAD

**Issue by AmelAlili** [betagouv/chatwoot#1]
Comme nous recevons les mails suite à une redirection:
- le mail de l'expéditeur n'apparait pas
- il est obligatoire de l'ajouter avant de répondre ou seule l'adresse mail animation recevra la réponse.

**Comment by sneko** [comment]
Problème réglé en changeant une configuration mailing-list chez OVH.

Cela aurait quand même dû marcher (voir https://github.com/chatwoot/chatwoot/issues/8735#issuecomment-1903806042), mais l'ajustement fait est acceptable (et même logique).
